"""make staff_number nullable in lecturer

Revision ID: 01dfde8946b2
Revises: remove_course_code_unique
Create Date: 2026-04-05 02:57:05.375233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dfde8946b2'
down_revision: Union[str, Sequence[str], None] = 'remove_course_code_unique'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lecturer', 'staff_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('lecturer', 'staff_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
