"""add cascade delete constraints

Revision ID: 674959737f7c
Revises: abc123add_verification_code
Create Date: 2026-04-05 21:26:57.452974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674959737f7c'
down_revision: Union[str, Sequence[str], None] = 'abc123add_verification_code'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendance_record_class_session_id_fkey'), 'attendance_record', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_record', 'class_session', ['class_session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('attendance_session_class_session_id_fkey'), 'attendance_session', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_session', 'class_session', ['class_session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('class_session_class_id_fkey'), 'class_session', type_='foreignkey')
    op.create_foreign_key(None, 'class_session', 'class', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('enrollment_class_id_fkey'), 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'class', ['class_id'], ['id'], ondelete='CASCADE')
    op.alter_column('webauthn_credential', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_webauthn_credential_student_id'), table_name='webauthn_credential', postgresql_where='(student_id IS NOT NULL)')
    op.drop_constraint(op.f('webauthn_credential_student_id_key'), 'webauthn_credential', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('webauthn_credential_student_id_key'), 'webauthn_credential', ['student_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_webauthn_credential_student_id'), 'webauthn_credential', ['student_id'], unique=False, postgresql_where='(student_id IS NOT NULL)')
    op.alter_column('webauthn_credential', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.create_foreign_key(op.f('enrollment_class_id_fkey'), 'enrollment', 'class', ['class_id'], ['id'])
    op.drop_constraint(None, 'class_session', type_='foreignkey')
    op.create_foreign_key(op.f('class_session_class_id_fkey'), 'class_session', 'class', ['class_id'], ['id'])
    op.drop_constraint(None, 'attendance_session', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_session_class_session_id_fkey'), 'attendance_session', 'class_session', ['class_session_id'], ['id'])
    op.drop_constraint(None, 'attendance_record', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_record_class_session_id_fkey'), 'attendance_record', 'class_session', ['class_session_id'], ['id'])
    # ### end Alembic commands ###
