"""remove username and staff_number

Revision ID: d9e745bd278c
Revises: 01dfde8946b2
Create Date: 2026-04-05 03:06:48.277180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e745bd278c'
down_revision: Union[str, Sequence[str], None] = '01dfde8946b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecturer_staff_number'), table_name='lecturer')
    op.drop_column('lecturer', 'staff_number')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('lecturer', sa.Column('staff_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_lecturer_staff_number'), 'lecturer', ['staff_number'], unique=True)
    # ### end Alembic commands ###
